DSST.sets = {
	["Default_Healer"] = {
		{name="Hollowfang Thirst", id=452},
		{name="Jorvuld's Guidance", id=346},
		{name="Master Architect", id=332},
		{name="Pearlescent Ward", id=648},
		{name="Pillager's Profit", id=649},
		{name="Powerful Assault", id=180},	
		{name="Roaring Opportunist", id=496},		
		{name="Saxhleel Champion", id=585},
		{name="Stone-Talker's Oath", id=588},
		{name="Spell Power Cure", id=185},
		{name="The Worm's Raiment", id=124},
		{name="Vestment of Olorime", id=391},
		{name="Way of Martial Knowledge", id=147},	
		{name="Perfected Pearlescent Ward", id=651},
		{name="Perfected Pillager's Profit", id=650},
		{name="Perfected Roaring Opportunist", id=497},
		{name="Perfected Saxhleel Champion", id=589},
		{name="Perfected Stone-Talker's Oath", id=592},
		{name="Perfected Vestment of Olorime", id=395},
		{name="Earthgore (Monster Helm)", id=341},
		{name="Encratis's Behemoth (Monster Helm)", id=577},
		{name="Sentinel of Rkugamz (Monster Helm)", id=268},
		{name="Symphony of Blades (Monster Helm)", id=436},
		{name="The Troll King (Monster Helm)", id=278},
		{name="Grand Rejuvenation (Arena Weapon)", id=318},
		{name="Perfected Grand Rejuvenation (Arena Weapon)", id=533},		
		{name="Mender's Ward (Arena Weapon)", id=416},	
		{name="Perfected Mender's Ward (Arena Weapon)", id=428},
		{name="Pearls of Ehlnofey (Mythic)", id=576},
		{name="Spaulder of Ruin (Mythic)", id=627},
	},
	["DOTD_Healer"] = {
		{name="Spell Power Cure", id=185},
		{name="The Worm's Raiment", id=124},
		{name="Way of Martial Knowledge", id=147},
		{name="Sentinel of Rkugamz (Monster Helm)", id=268},
		{name="The Troll King (Monster Helm)", id=278},
		{name="Symphony of Blades (Monster Helm)", id=436},
		{name="Roaring Opportunist", id=496},
		{name="Perfected Roaring Opportunist", id=497},
		{name="Jorvuld's Guidance", id=346},
		{name="Vestment of Olorime", id=391},
		{name="Perfected Vestment of Olorime", id=395},
		{name="Grand Rejuvenation (Arena Weapon)", id=318},
		{name="Perfected Grand Rejuvenation (Arena Weapon)", id=533},		
		{name="Powerful Assault", id=180},		
		{name="Hollowfang Thirst", id=452},
		{name="Master Architect", id=332},
		{name="Stone-Talker's Oath", id=588},
		{name="Perfected Stone-Talker's Oath", id=592},
		{name="Saxhleel Champion", id=585},
		{name="Perfected Saxhleel Champion", id=589},
		{name="Pearlescent Ward", id=648},
		{name="Perfected Pearlescent Ward", id=651},
		{name="Pillager's Profit", id=649},
		{name="Perfected Pillager's Profit", id=650},
		{name="Earthgore (Monster Helm)", id=341},
		{name="Encratis's Behemoth (Monster Helm)", id=577},
		{name="Mender's Ward (Arena Weapon)", id=416},	
		{name="Perfected Mender's Ward (Arena Weapon)", id=428},
		{name="Pearls of Ehlnofey (Mythic)", id=576},
		{name="Spaulder of Ruin (Mythic)", id=627},
	},
	["Default_Tank"] = {    
        {name="Aegis of Galenwe", id=388},
		{name="Archdruid Devyric", id=666}, 
        {name="Arkasis’s Genius", id=518},    
        {name="Claw of Yolnahkriin", id=446},
        {name="Crimson Oath’s Rive", id=602},
        {name="Dragon's Defilement", id=457},
        {name="Drake’s Rush", id=571},
        {name="Ebon Armory", id=122},    
        {name="Elemental Catalyst", id=516},
        {name="Frozen Watcher", id=433},
        {name="Powerful Assault", id=180},
        {name="Roar of Alkosh", id=232},
        {name="Saxhleel Champion", id=585},
        {name="The Worm's Raiment", id=124},
        {name="Turning Tide", id=622},
        {name="Vestment of Olorime", id=391},
        {name="War Machine", id=331},
        {name="Way of Martial Knowledge", id=147},
		{name="Pearlescent Ward", id=648 },
        {name="Perfected Aegis of Galenwe", id=392},
        {name="Perfected Claw of Yolnahkriin", id=451},
		{name="Perfected Pearlescent Ward", id=651},
        {name="Perfected Saxhleel Champion", id=589},
        {name="Perfected Vestment of Olorime", id=395},
        {name="Bloodspawn (Monster Helm)", id=163},
        {name="Earthgore (Monster Helm)", id=341},
        {name="Encratis's Behemoth (Monster Helm)", id=577},
        {name="Lady Thorn (Monster Helm)", id=535},
        {name="Lord Warden (Monster Helm)", id=164},
        {name="Magma Incarnate (Monster Helm)", id=609},
		{name="Nazaray (Monster Helm)", id=633},
        {name="The Troll King (Monster Helm)", id=278},
        {name="Thurvokun (Monster Helm)", id=349},
        {name="Tremorscale (Monster Helm)", id=276},
        {name="Puncturing Remedy (Arena Weapon)", id=314},
        {name="Perfected Puncturing Remedy (Arena Weapon)", id=529},        
        {name="Pearls of Ehlnofey (Mythic)", id=576},
        {name="Spaulder of Ruin (Mythic)", id=627},
		{name="Syrabane's Ward", id=676},
    },
	["DOTD_Tank"] = {	
		{name="Ebon Armory", id=122},	
		{name="The Worm's Raiment", id=124},
		{name="Way of Martial Knowledge", id=147},
		{name="Lord Warden (Monster Helm)", id=164},
		{name="Bloodspawn (Monster Helm)", id=163},
		{name="Claw of Yolnahkriin", id=446},
		{name="Perfected Claw of Yolnahkriin", id=451},
		{name="Crimson Oath’s Rive", id=602},
		{name="Dragon's Defilement", id=457},
		{name="Roar of Alkosh", id=232},
		{name="Powerful Assault", id=180},
		{name="Saxhleel Champion", id=585},
		{name="Perfected Saxhleel Champion", id=589},
		{name="Vestment of Olorime", id=391},
		{name="Perfected Vestment of Olorime", id=395},		
		{name="Archdruid Devyric", id=666}, 		
		{name="Tremorscale (Monster Helm)", id=276},
		{name="Earthgore (Monster Helm)", id=341},
		{name="The Troll King (Monster Helm)", id=278},
		{name="Lady Thorn (Monster Helm)", id=535},
		{name="Encratis's Behemoth (Monster Helm)", id=577},
		{name="Puncturing Remedy (Arena Weapon)", id=314},
		{name="Perfected Puncturing Remedy (Arena Weapon)", id=529},		
		{name="Frozen Watcher", id=433},
		{name="War Machine", id=331},
		{name="Drake’s Rush", id=571},
		{name="Pearlescent Ward", id=648},
		{name="Perfected Pearlescent Ward", id=651},
		{name="Arkasis’s Genius", id=518},	
		{name="Elemental Catalyst", id=516},
        {name="Turning Tide", id=622},
		{name="Thurvokun (Monster Helm)", id=349},
		{name="Magma Incarnate (Monster Helm)", id=609},
		{name="Nazaray (Monster Helm)", id=633},
		{name="Pearls of Ehlnofey (Mythic)", id=576},
		{name="Spaulder of Ruin (Mythic)", id=627},
		{name="Syrabane's Ward", id=676},
	},
	["IP_Healer_U33"] = {   
        {name="** Vestment of Olorime", id=391},
        {name="** Perfected Vestment of Olorime", id=395},  
        {name="** Spell Power Cure", id=185},   
        {name="<3 Jorvuld's Guidance", id=346},
        {name="<3 Roaring Opportunist", id=496},
        {name="<3 Perfected Roaring Opportunist", id=497},
        {name="<3 Way of Martial Knowledge", id=147},
        {name="<3 Master Architect", id=332},
        {name="<3 Powerful Assault", id=180},
        {name="OK Saxhleel Champion", id=585},
        {name="OK Perfected Saxhleel Champion", id=589},
        {name="OK Elemental Catalyst", id=516},
        {name="OK The Worm's Raiment", id=124},
        {name="<3 Symphony of Blades (Monster Helm)", id=436},
        {name="<3 Sentinel of Rkugamz (Monster Helm)", id=268},
        {name="<3 Nazaray (Monster Helm)", id=633},
        {name="OK The Troll King (Monster Helm)", id=278},
        {name="<3 Grand Rejuvenation (Dragonstar)", id=318},
        {name="<3 Perfected Grand Rejuvenation (Dragonstar)", id=533},  
        {name="OK Mender's Ward (Blackrose)", id=416},  
        {name="OK Perfected Mender's Ward (Blackrose)", id=428},
        {name="OK Precise Regeneration (Maelstrom)", id=416},   
        {name="OK Perfected Precise Regeneration (Maelstrom)", id=428}, 
        {name="<3 Pearls of Ehlnofey (Mythic)", id=576}, 
        {name="<3 Spaulder of Ruin (Mythic)", id=627}, 
        {name="     Hollowfang Thirst", id=452}, 
        {name="     War Machine", id=331}, 
        {name="     Stone-Talker's Oath", id=588},
        {name="     Perfected Stone-Talker's Oath", id=592}, 
        {name="     Z'en's Redress", id=455},
        {name="     Ebon Armory", id=122},
        {name="     Encratis's Behemoth (Monster Helm)", id=577},
        {name="     Earthgore (Monster Helm)", id=341}
    },
    ["IP_Tank_U33"] = { 
        {name="** Claw of Yolnahkriin", id=446},
        {name="** Perfected Claw of Yolnahkriin", id=451},
        {name="** Powerful Assault", id=180},
        {name="<3 War Machine", id=331},
        {name="<3 Saxhleel Champion", id=585},
        {name="<3 Perfected Saxhleel Champion", id=589},
        {name="<3 Turning Tide", id=622},
        {name="OK Crimson Oath’s Rive", id=602},
        {name="OK The Worm's Raiment", id=124},
        {name="OK Elemental Catalyst", id=516},
        {name="OK Aegis of Galenwe", id=388},
        {name="OK Perfected Aegis of Galenwe", id=392},
        {name="<3 Encratis's Behemoth (Monster Helm)", id=577},
        {name="<3 Earthgore (Monster Helm)", id=341},
        {name="<3 Engine Guardian (Monster Helm)", id=166},
        {name="<3 Nazaray (Monster Helm)", id=633},
        {name="<3 Puncturing Remedy (Arena Weapon)", id=314},
        {name="<3 Perfected Puncturing Remedy (Arena Weapon)", id=529},
        {name="<3 Spaulder of Ruin (Mythic)", id=627},
        {name="     Way of Martial Knowledge", id=147},
        {name="     Roar of Alkosh", id=232},
        {name="     Vestment of Olorime", id=391},
        {name="     Perfected Vestment of Olorime", id=395},        
        {name="     Drake’s Rush", id=571},
        {name="     Arkasis’s Genius", id=518},   
        {name="     Master Architect", id=332},
        {name="     Leeching Plate", id=196},
        {name="     Ebon Armory", id=122},
        {name="     Tremorscale (Monster Helm)", id=276},
        {name="     The Troll King (Monster Helm)", id=278},
        {name="     Lady Thorn (Monster Helm)", id=535},
        {name="     Lord Warden (Monster Helm)", id=164},
        {name="     Bloodspawn (Monster Helm)", id=163},
        {name="     Thurvokun (Monster Helm)", id=349},
        {name="     Magma Incarnate (Monster Helm)", id=609},
        {name="     Pearls of Ehlnofey (Mythic)", id=576}
    },
}